<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace frontend\assets\plugins;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class PluginAsset extends AssetBundle
{
    public $sourcePath = '@frontend/web/plugins';

    public $jsOptions = [
        'position' => View::POS_BEGIN
    ];
    public $depends = [
        'yii\web\JqueryAsset',
        'frontend\assets\BootstrapAsset'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
