<?php

namespace common\models\pool;

use common\models\itemInfo\BaseInfo;
use common\models\itemInfo\iItemInfo;
use common\models\itemInfo\ItemInfo;
use yii\base\Model;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "pool".
 *
 * @property integer $id
 * @property integer $pool_id
 * @property integer $pocket_id
 * @property string $item_type
 * @property integer $give_count
 * @property integer $updated_at
 * @property integer $created_at
 *
 *
 * @property PoolPocketItemInfo[] $itemInfo
 * @property PoolValidator[] $itemValidators
 */
class PoolPocketItem extends \common\models\BaseModel
{
	/** @var iItemInfo|Model */
	public $info;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pool_pocket_item';
    }

	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
				'updatedAtAttribute' => 'updated_at',
				'createdAtAttribute' => 'created_at',
			],
		];
	}

    /**
     * @inheritdoc
     */
	public function rules()
	{
		return [
			[['pool_id', 'pocket_id', 'item_type', 'give_count'], 'required'],
			[['pool_id', 'pocket_id', 'give_count', 'updated_at', 'created_at'], 'integer'],
			['item_type', 'in', 'range' => [
				ItemInfo::ITEM_TYPE_ITEM,
				ItemInfo::ITEM_TYPE_REPA,
				ItemInfo::ITEM_TYPE_EXP,
				ItemInfo::ITEM_TYPE_KR,
				ItemInfo::ITEM_TYPE_EKR,
				ItemInfo::ITEM_TYPE_ABILITY_OWN,
				ItemInfo::ITEM_TYPE_MEDAL,
				ItemInfo::ITEM_TYPE_WEIGHT,
				ItemInfo::ITEM_TYPE_PROF_EXP,
			]],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' 			=> 'ID',
			'pool_id' 		=> 'ID пула',
			'pocket_id' 	=> 'ID пакета',
			'item_type' 	=> 'Тип сущности',
			'give_count' 	=> 'Выдаваемое кол-во',
			'updated_at' 	=> 'Обновление',
			'created_at' 	=> 'Создание',
		];
	}

    /**
     * @inheritdoc
     * @return \common\models\query\pool\PoolPocketItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\pool\PoolPocketItemQuery(get_called_class());
    }

	public function getItemInfo()
	{
		return $this->hasMany(PoolPocketItemInfo::class, ['pocket_item_id' => 'id']);
	}

	public function getItemValidators()
	{
		return $this->hasMany(PoolValidator::class, ['target_id' => 'id'])
			->andWhere(['=', 'target_type', PoolValidator::TARGET_POCKET_ITEM]);
	}

	public function afterFind()
	{
		parent::afterFind(); // TODO: Change the autogenerated stub

		$this->info = BaseInfo::getItemInfo($this->item_type);
		foreach ($this->itemInfo as $Info) {
			$this->info->{$Info->field} = $Info->value;
		}

		foreach ($this->itemValidators as $Validator) {
			$this->info->addToValidatorList($Validator);
		}
	}
}