<?php
/**
 * Created by PhpStorm.
 * User: nnikitchenko
 * Date: 24.03.2016
 */

namespace common\models\itemInfo;

use common\models\validatorItem\iValidator;
use yii\base\Model;

abstract class BaseInfo extends Model implements iItemInfo
{
    const ITEM_TYPE_ITEM            = 'item';
    const ITEM_TYPE_CUSTOM_ITEM     = 'custom_item';
    const ITEM_TYPE_ABILITY_OWN     = 'ability';
    const ITEM_TYPE_EXP             = 'exp';
    const ITEM_TYPE_REPA            = 'repa';
    const ITEM_TYPE_KR              = 'kr';
    const ITEM_TYPE_EKR             = 'ekr';
    const ITEM_TYPE_MEDAL           = 'medal';
    const ITEM_TYPE_WEIGHT          = 'weight';
    const ITEM_TYPE_PROF_EXP        = 'prof_exp';

    public $name;

    public $other_settings;
    /** @var iValidator[] */
    protected $validator_list = [];

    public function getOtherSettings()
    {
        return $this->other_settings;
    }

    public function rules()
    {
        return [
            
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Название предмета',
            'count' => 'Кол-во',
            'other_settings' => 'Прочие настройки',
        ];
    }

    public function setAttributes($values, $safeOnly = true)
    {
        parent::setAttributes($values, $safeOnly); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    public static function getItemInfo($type)
    {
        $type = str_replace(' ', '', ucwords(str_replace('_', ' ', $type)));
        $className = sprintf('common\models\itemInfo\\%sInfo', ucfirst($type));
        try {
            return new $className();
        } catch (\Exception $ex) {
            return null;
        }
    }

    public function getTitle()
    {
        return self::getTypeTitles()[$this->getItemType()];
    }

    public static function getTypeTitles()
    {
        return [
            self::ITEM_TYPE_ITEM        => 'Предмет',
            self::ITEM_TYPE_ABILITY_OWN => 'Личный реликт',
            self::ITEM_TYPE_CUSTOM_ITEM => 'Custom',
            self::ITEM_TYPE_EXP         => 'Опыт',
            self::ITEM_TYPE_REPA        => 'Репутация',
            self::ITEM_TYPE_KR          => 'КР',
            self::ITEM_TYPE_EKR         => 'ЕКР',
        ];
    }

    public function load($data, $formName = null)
    {
        $r = parent::load($data, $formName); // TODO: Change the autogenerated stub
        $this->other_settings = $this->getOtherSettings();

        return $r;
    }

    public function hasValidatorList()
    {
        return !empty($this->validator_list);
    }

    public function getValidatorList()
    {
        return $this->validator_list;
    }

    public function addToValidatorList($validator)
    {
        $this->validator_list[] = $validator;
        return $this;
    }

    public function getValidatorCount()
    {
        return count($this->validator_list);
    }
}