<?php
/**
 * Created by PhpStorm.
 * User: nnikitchenko
 * Date: 27.02.2016
 */

/**
 * Yii bootstrap file.
 * Used for enhanced IDE code autocompletion.
 */
class Yii extends yii\BaseYii
{
    /**
     * @var BaseApplication|WebApplication|ConsoleApplication the application instance
     */
    public static $app;
}

spl_autoload_register(['Yii', 'autoload'], true, true);
Yii::$classMap = include(__DIR__ . '/../../vendor/yiisoft/yii2/classes.php');
Yii::$container = new yii\di\Container;

/**
 * Class BaseApplication
 * Used for properties that are identical for both WebApplication and ConsoleApplication
 *
 */
abstract class BaseApplication extends yii\base\Application
{
}

/**
 * Class WebApplication
 * Include only Web application related components here
 *
 * @property \common\components\Breadcrumbs $breadcrumbs
 * @property \common\components\View $view
 * @property User $user
 * @property \yii\db\Connection $db
 * @property \yii\db\Connection $db_oldbk
 * @property \yii\db\Connection $db_top
 * @property \dpodium\yii2\geoip\components\CGeoIP $geoip
 *
 */
class WebApplication extends yii\web\Application
{
    public function init()
    {
        Yii::$container->set('yii\widgets\Pjax', ['timeout' => 10000]);
        
        parent::init(); // TODO: Change the autogenerated stub
    }
}

/**
 * Class ConsoleApplication
 * Include only Console application related components here
 *
 */
class ConsoleApplication extends yii\console\Application
{
}

/**
 * Class User
 *
 * @property \common\models\User $identity
 */
class User extends \yii\web\User
{

}