<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace frontend\assets;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{
    //public $basePath = '@webroot';
    //public $baseUrl = '@web';
    public $css = [
        'css/animate.css',
        'css/style.css',
        'css/main.css',
    ];
    public $js = [
        'js/inspinia.js',
        'js/script.js',
        'js/ajax.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'frontend\assets\BootstrapAsset',
        'frontend\assets\plugins\MetisMenuAsset',
        'frontend\assets\plugins\PaceAsset',
        'frontend\assets\plugins\SlimscrollAsset',
        'frontend\assets\plugins\ToastrAsset',
    ];
    public $jsOptions = [
        'position' => View::POS_BEGIN
    ];

    public function init()
    {
        //$this->sourcePath = '@frontend/web/themes/'.\Yii::$app->view->theme->name;
        $this->baseUrl = '@web/themes/'.\Yii::$app->view->theme->name;
        parent::init(); // TODO: Change the autogenerated stub
    }
}
